controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    steer_position_controller:
      type: position_controllers/JointGroupPositionController

    wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

steer_position_controller:
  ros__parameters:
    joints:
      - steer_joint_1
      - steer_joint_2
      - steer_joint_3

wheel_velocity_controller:
  ros__parameters:
    joints:
      - wheel_joint_1
      - wheel_joint_2
      - wheel_joint_3